export const attentionPaperChapters = [
  { label: 'The problem', title: 'Before Transformers, sequence models had to walk.', body: 'Older recurrent models read a sentence one step at a time. Imagine reading a book where you are allowed to look at only one word, then must finish processing that word before you can see the next. That makes training harder to parallelize and makes distant relationships travel through many intermediate steps.', takeaway: 'The paper was looking for a way to connect distant words without walking through every word in between.' },
  { label: 'The big idea', title: 'Let every word look at every other word.', body: 'The Transformer replaced the main recurrent path with attention. A word can ask which other words are useful right now, give those words different weights, and blend their information into a new context-aware representation.', takeaway: 'Attention turns “read the whole sequence step by step” into “compare the sequence in parallel.”' },
  { label: 'The mechanism', title: 'Every token gets a question, a label, and information.', body: 'For each token, Query means “what am I looking for?”, Key means “what do I represent?”, and Value means “what information should I pass along?”. Query-Key comparisons create relevance scores. Softmax turns scores into weights. The weighted Values become the updated meaning of the token.', formula: 'Attention(Q, K, V) = softmax(QKᵀ / √dₖ)V', takeaway: 'Q finds, K matches, and V carries the information that gets mixed.' },
  { label: 'Many views', title: 'Why use multiple attention heads?', body: 'One attention pattern may not be enough. Multiple heads let the model look at the same sentence through different learned views. One may notice nearby grammar, another may connect a pronoun to a name, and another may track a longer relationship. These are useful intuitions, not fixed human-assigned jobs.', takeaway: 'Multi-head attention gives the model several relationship-finding views at once.' },
  { label: 'Order matters', title: 'Attention needs help to know where words are.', body: 'If you shuffled the words in a sentence, attention would still see the same collection of tokens unless position information were added. The original paper added positional encodings so “dog bites man” and “man bites dog” do not look identical.', formula: 'token meaning + position signal → representation', takeaway: 'The Transformer has no built-in left-to-right clock, so position must be represented explicitly.' },
  { label: 'The machine', title: 'Attention and feed-forward layers repeat.', body: 'The original Transformer stacks blocks. Attention lets positions exchange information. A feed-forward network then transforms each position. Residual connections carry the earlier representation forward, and normalization keeps the values manageable. Repeating this process creates richer representations.', takeaway: 'A Transformer is not one attention operation; it is a stack of small transformations.' },
  { label: 'Why it mattered', title: 'The paper changed the shape of sequence modeling.', body: 'On the translation tasks studied in the paper, the Transformer reached strong results while allowing more parallel training than recurrent approaches. Its ideas later became the foundation for many model families, but the original paper was an encoder-decoder translation paper, not a complete description of modern chat models.', takeaway: 'The lasting contribution was an attention-centered architecture that scaled with modern accelerators.' },
  { label: 'Engineering lens', title: 'The original win creates a later cost.', body: 'Self-attention lets every position compare with every other position. That is powerful, but the number of pairwise interactions grows with sequence length. During autoregressive generation, the model also keeps reusable Key and Value activations in a KV cache. That leads directly to the next module.', takeaway: 'The Transformer explains both the power of attention and why long-context inference needs careful memory engineering.' }
];

export const upcomingPapers = [
  ['FlashAttention', 'How IO-aware exact attention makes memory movement part of the algorithm.'],
  ['Mamba', 'How selective state-space models carry sequence history differently.'],
  ['Chinchilla', 'Why training data and parameter count should be balanced.'],
  ['PagedAttention', 'How serving systems manage many requests’ KV-cache memory.']
];
